version: "3"
services:
  spring-demo:
    build: .
    ports:
    - "4040:8080"
    volumes:
    - ./spring-demo:/opt/logs/spring-demo
    depends_on:
      - redis
      - hippo4j
  redis:
    image: "library/redis:alpine"
  hippo4j:
    image: "hippo4j/hippo4j-server"
    ports:
    - "6691:6691"
