version: "3"
services:
  spring-demo:
    build: .
    ports:
    - "4040:8080"
    volumes:
    - ./spring-demo:/opt/logs/spring-demo
    depends_on:
      - redis
  redis:
    image: "library/redis:alpine"
