server:
  port: 5020

grpc:
  client:
    grpc-operate-service:
      address: discovery:/grpc-server
#      address: 'static://127.0.0.1:5015'
      negotiation-type: plaintext
  server:
    url: localhost:5015