server:
  port: 5020
spring:
  application:
    name: grpc-client
  cloud:
    zookeeper:
      connect-string: localhost:2181
grpc:
  client:
    grpc-operate-service:
      address: discovery:/grpc-server
#      address: 'static://127.0.0.1:5015'
      negotiation-type: plaintext