// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.jimas.grpc.common.helloworld;

/**
 * <pre>
 *操作类型
 * </pre>
 *
 * Protobuf enum {@code OperateType}
 */
public enum OperateType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Addition = 0;</code>
   */
  Addition(0),
  /**
   * <code>Division = 1;</code>
   */
  Division(1),
  /**
   * <code>Multi = 2;</code>
   */
  Multi(2),
  /**
   * <code>Sub = 3;</code>
   */
  Sub(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Addition = 0;</code>
   */
  public static final int Addition_VALUE = 0;
  /**
   * <code>Division = 1;</code>
   */
  public static final int Division_VALUE = 1;
  /**
   * <code>Multi = 2;</code>
   */
  public static final int Multi_VALUE = 2;
  /**
   * <code>Sub = 3;</code>
   */
  public static final int Sub_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static OperateType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static OperateType forNumber(int value) {
    switch (value) {
      case 0: return Addition;
      case 1: return Division;
      case 2: return Multi;
      case 3: return Sub;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OperateType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OperateType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OperateType>() {
          public OperateType findValueByNumber(int number) {
            return OperateType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return HelloWorld.getDescriptor().getEnumTypes().get(0);
  }

  private static final OperateType[] VALUES = values();

  public static OperateType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private OperateType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:OperateType)
}

