// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.jimas.grpc.common.helloworld;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double result = 1;</code>
   * @return The result.
   */
  double getResult();

  /**
   * <code>int32 responsePort = 2;</code>
   * @return The responsePort.
   */
  int getResponsePort();
}
