GET http://localhost:9001/order/findByNo?orderNo=99
Accept: application/json

###

GET http://localhost:9001/order/hystrix/findByNo?orderNo=99
Accept: application/json

###
GET http://localhost:9001/order/hystrix/findByNo?orderNo=hystrix
Accept: application/json

###
